### ISSUE TITLE
chromhmm-signalize rebin error

### ISSUE THREAD

**Issue by mdurante1** [daler/chromhmm-tools#1]
Hello,

I am receiving an error when using the ChromHMM-signalize rebin command. The first bigwig file is converted to a bedgraph and then I receive the error below. Do you have any suggestions to resolve this?

Thanks,
Michael 

```
[2018-02-24 23:52:41,283] INFO: /projects/med/hlab/analysis/working/UM_shBAP1/ChIP-Seq/921/chromHMM/921_Control_H2Aub_average.bw -> binned/921_Control-H2Aub-200-{chrom}.binned
[2018-02-24 23:52:41,353] INFO: converting to bedgraph
[2018-02-24 23:53:46,457] INFO: chr1
Traceback (most recent call last):
 File "/projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py", line 280, in <module>
 parser.dispatch()
 File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
 return dispatch(self, *args, **kwargs)
 File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
 for line in lines:
  File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
 for line in result:
File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py", line 194, in rebin
    write_interpolated_results(x, y, chrom)
  File "/projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py", line 176, in write_interpolated_results
    max_pos = genome[chrom][-1]
KeyError: u'chr1'

```

**Comment by daler** [comment]
One reason might be that the chromsizes dictionary for the assembly you specified does not match the chromosomes you have in your file, e.g., `1` vs `chr1`. Another reason might be py2 vs py3 . . . I have not touched this code in quite a while and I don't remember testing it in py3. In that case, a possible fix would be to replace the `os.system` calls with `subprocess.check_call`.

**Comment by mdurante1** [comment]
Thank you for your response. The assembly that I'm using is hg19 and it uses the `chr` prefix for the chromosomes. I believe this matches the assembly in the chromosome sizes file that is pulled in by pybedtools. I am also running this in python 2.7.3 so I don't think it's a compatibility issue. Do you have any other suggestions or recommendations for conducting a clean install?

**Comment by daler** [comment]
Not off the top of my head . . . if you send the file that you're having trouble with I'll take a look.

**Comment by mdurante1** [comment]
Thank you for your help. Please find the file at this link:
https://www.dropbox.com/s/8qqvwmbb9h82l67/921_Control_H2Aub_average.bw?dl=0

**Comment by daler** [comment]
I was getting a different error, where it was complaining about integers rather than floats (see fix in 7eeeb8adc683a7180f0ecb0d46dc706f92d7ff5d) I created a new conda environment:

```bash
conda create env -n py2example -c bioconda numpy pybedtools ucsc-bigwigtobedgraph
source activate py2example
```
created the following tab-delimited file called `config.txt`:

```
celltype1       mark1   921_Control_H2Aub_average.bw
```

and ran with 

```
python chromhmm-signalize.py rebin config.txt hg19
```

with no errors. Are you able to reproduce the original error with the above steps?

**Comment by mdurante1** [comment]
I am having issues running the code after I create a new environment. FYI I am running Centos 6.5, are you using Ubuntu?

`(py2example) [mdurante@pegasus chromHMM]$ python /projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py rebin config2.txt hg19
Traceback (most recent call last):
  File "/projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py", line 79, in <module>
    import argh
ImportError: No module named argh
(py2example) [mdurante@pegasus chromHMM]$ pip install argh
Collecting argh
  Using cached argh-0.26.2-py2.py3-none-any.whl
Installing collected packages: argh
Successfully installed argh-0.26.2
(py2example) [mdurante@pegasus chromHMM]$ python /projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py rebin config2.txt hg19
Traceback (most recent call last):
  File "/projects/med/hlab/software/chromhmm-tools/chromhmm_signalize.py", line 83, in <module>
    import pybedtools
  File "/nethome/mdurante/miniconda3/envs/py2example/lib/python2.7/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/nethome/mdurante/miniconda3/envs/py2example/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/nethome/mdurante/miniconda3/envs/py2example/lib/python2.7/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/nethome/mdurante/miniconda3/envs/py2example/lib/python2.7/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/nethome/mdurante/miniconda3/envs/py2example/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /lib64/libk5crypto.so.3: symbol krb5int_buf_len, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference`

**Comment by mdurante1** [comment]
Thanks for your help I was able to get this to work using the new environment.
